<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable ,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'state_id',
        'hearAboutUs',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public static array $hearedAboutUs = ['google','facebook','event','from a friend'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($user){
            $user->profile()->create([
                'bio' => 'new member',
            ]);
        });
    }
    public function orders()
    {
        return $this->hasMany(Order::class);
    }
    public function receipts()
    {
        return $this->hasMany(Receipt::class);
    }
    public function latestOrder()
    {
        return $this->hasOne(Order::class)->latestOfMany();
    }
    public function profile()
    {
        return $this->hasOne(Profile::class);
    }
    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }

    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }
    public function state()
    {
        return $this->belongsTo(State::class);
    }
    public function zone()
    {
        return  $this->belongsToMany(Zone::class);
    }

}
